sudo: required
services:
  - docker

before_install:
  - docker build -t rishu53/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true rishu53/react-test npm test

after_success:
  - docker build -t rishu53/energy-frontend ./frontend
  - docker build -t rishu53/energy-backend ./backend
  - docker build -t rishu53/energy-nginx ./nginx
  
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push rishu53/energy-frontend
  - docker push rishu53/energy-backend
  - docker push rishu53/energy-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "EnergyTracker"
  env: "Energytracker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-823931889189"
  bucket_path: "EnergyTracker"
  on:
    branch: master
  access_key_id: $KEY
  secret_access_key: $PASSWORD