apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: frontend 
          image: rishu53/energy-frontend
          ports:
            - containerPort: 3000